server:
  port: 9050
spring:
  cloud:
#    inetutils:
#      preferred-networks: 192.168.31 #cloud多网卡配置
    nacos:
      discovery:
        server-addr: nacos:8848
management:
  endpoints:
    web:
      exposure:
        #exclude: shutdown,threaddump   #此处控制的是不开放哪些端点
        include: "*" #此处控制的是开放哪些端点，如果需要开启少数端点可以这样配置：health,info。如果开启多个则使用*号开启除了exclude的端点
    health:
      show-details: always