server:
  port: 9060
spring:
  redis:
    host: redis
    port: 6379
    ####password: 123456
  cloud:
#    inetutils:
#      preferred-networks: 192.168.31 #cloud多网卡配置
    nacos:
      discovery:
        server-addr: nacos:8848
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    locale: zh_CN
    time-zone: GMT+8
logging:
  level:
    root: INFO
    org.springframework.web: INFO
management:
  endpoints:
    web:
      exposure:
        #exclude: shutdown,threaddump   #此处控制的是不开放哪些端点
        include: "*" #此处控制的是开放哪些端点，如果需要开启少数端点可以这样配置：health,info。如果开启多个则使用*号开启除了exclude的端点
    health:
      show-details: always
#对Feign的支持
feign:
  sentinel:
    enabled: true # 添加feign对sentinel的支持